In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [ ]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X = df.drop('species', axis = 1)
y = df['species']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
model_knn = KNeighborsClassifier(n_neighbors=12)

In [ ]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=12)

In [ ]:
model_knn.score(X_test, y_test)

1.0

In [ ]:
from sklearn.svm import SVC

In [ ]:
model_svm = SVC(gamma = 'auto')

In [ ]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [ ]:
model_svm.score(X_test, y_test)

1.0

# GridSearchCv
> Now let's use GridSearchCV() for best hyperparameter tunning.

> cross-validation save the model from overfitting

In [ ]:
from sklearn.model_selection import GridSearchCV

In [ ]:
classifier = GridSearchCV(model_svm, {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear']
}, cv = 5, return_train_score = False)

In [ ]:
classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [ ]:
classifier.cv_results_

{'mean_fit_time': array([0.0043467 , 0.0051209 , 0.00547199, 0.00603828, 0.00449467,
        0.00373526, 0.00408983, 0.00385141]),
 'std_fit_time': array([0.00034352, 0.00209637, 0.00183889, 0.00132719, 0.0007994 ,
        0.00014755, 0.0001115 , 0.0002017 ]),
 'mean_score_time': array([0.00361261, 0.00325112, 0.00427732, 0.0032403 , 0.00348005,
        0.00285926, 0.00305743, 0.00286708]),
 'std_score_time': array([0.00087492, 0.00024803, 0.00240899, 0.00013743, 0.00047586,
        0.00010761, 0.00011007, 0.00015947]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [ ]:
results = pd.DataFrame(classifier.cv_results_)

In [ ]:
results

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.004347      0.000344  ...        0.016330                1
1       0.005121      0.002096  ...        0.016330                1
2       0.005472      0.001839  ...        0.016330                1
3       0.006038      0.001327  ...        0.038873                4
4       0.004495      0.000799  ...        0.036515                5
5       0.003735      0.000148  ...        0.042164                6
6       0.004090      0.000111  ...        0.038873                7
7       0.003851      0.000202  ...        0.048990                7

[8 rows x 15 columns]

In [ ]:
results[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

In [ ]:
classifier_r = RandomizedSearchCV(model_svm, {
    'C': [1, 10, 20, 30],
    'kernel': ['rbf', 'linear']
}, n_iter= 4, cv = 5, return_train_score = False)

In [ ]:
classifier_r.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [ ]:
results_r = pd.DataFrame(classifier_r.cv_results_)

In [ ]:
results_r

   mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.007375      0.002446  ...        0.016330                1
1       0.010037      0.003818  ...        0.048990                4
2       0.019350      0.010852  ...        0.016330                1
3       0.015640      0.003958  ...        0.038873                3

[4 rows x 15 columns]

In [ ]:
results_r[['param_C', 'param_kernel', 'mean_test_score']]

   param_C param_kernel  mean_test_score
0        1       linear         0.980000
1       30       linear         0.960000
2       10          rbf         0.980000
3       10       linear         0.973333